### ISSUE TITLE
P100 is OK

### ISSUE THREAD

**Issue by Eric9453** [sanlike0911/node-red-contrib-tplink-tapo-connect-api#1]
Hi, this is a very good project, thank you.

I just test this project on P100, that's work all good.

Thank you very much. 👍

**Comment by sanlike0911** [comment]
Hi, Thank you to verify the operation of P100.

Include in this project that it works on P100.

Thank you very much.

**Comment by sanlike0911** [comment]
v0.0.6
Added P105 to supported hardware.
