### ISSUE TITLE
Support for P110

### ISSUE THREAD

**Issue by johnkazer** [sanlike0911/node-red-contrib-tplink-tapo-connect-api#12]
I haven't investigated yet, but would it be straightforward to add the P110 too?
Maybe these will help
https://github.com/petretiandrea/home-assistant-tapo-p100/issues/64
https://github.com/fishbigger/TapoP100 (python but hopefully translatable)

**Comment by sanlike0911** [comment]
Hi.
Thank you for using this node-red-contrib-tplink-tapo-connect-api.

This node-red-contrib-tplink-tapo-connect-api is a wrapper for "tp-link-tapo-connect".
Let's look forward to the "tp-link-tapo-connect" update.


[dickydoouk/tp-link-tapo-connect](https://github.com/dickydoouk/tp-link-tapo-connect)

sanlike0911

**Comment by johnkazer** [comment]
I raised this on tp-link-tapo-connect.
