### ISSUE TITLE
consider switching upstream for better support of cct bulbs

### ISSUE THREAD

**Issue by nonchip** [sanlike0911/node-red-contrib-tplink-tapo-connect-api#13]
`tp-link-tapo-connect` upstream seems rather unmaintained (or at least very slowly maintained) currently (last change was a "minor naming improvement" 2 months ago, last change before that was in october, 2 unanswered PRs since december, 2 unanswered issues since january, last closed issue was in december), it might be helpful to temporarily switch upstream to @ccristi9918's version, due to this change actually implementing support for more than 3 settings in CCT bulbs, that doesn't look like it would be merged soon: https://github.com/dickydoouk/tp-link-tapo-connect/pull/18

though i'm not sure how well that would work with npm and all that, if you have an alternative idea how a user might switch over on their end that'd be highly appreciated too. currently i do the really ugly hack of directly editing the js files in `node_modules`

**Comment by sanlike0911** [comment]
Hi.
Thank you for using this node-red-contrib-tplink-tapo-connect-api.

The node-red-contrib-tplink-tapo-connect-api is thinking of changing to an active npm package.

please wait until finish.

sanlike0911
