### ISSUE TITLE
Hardware v2.0 - handshake not respond cookie session ID needed to next command

### ISSUE THREAD

**Issue by Triyono123** [sanlike0911/node-red-contrib-tplink-tapo-connect-api#16]
Before in v1.0 or v1.2, handshake could be made normally, and responded with:
{
 "error_code":0,
 "result":{
  "key":"........."
 }
}
and also with TP Session ID.

But somehow when we try to connecting to Tapo hardware v2.0, the handshake did not go well. In result, responded with:
<html>
 <body>
  <center>
   200 OK
  </center>
 </body>
</html>
with Header:
Server : SHIP 2.0

Any Experts please advise.

**Comment by sanlike0911** [comment]
Hi.
Thank you for using this node-red-contrib-tplink-tapo-connect-api.

This node-red-contrib-tplink-tapo-connect-api is a wrapper for "tp-link-tapo-connect".This problem may be resolved by asking "dickydoouk/tp-link-tapo-connect".

My P100 is hardware v1.0.0, but after updating the firmware of P100 to v1.3.2, it stopped working. it doesn't work properly now.

sanlike0911

**Comment by sanlike0911** [comment]
This problem has been fixed in version 0.3.4.
[#0b6f751](https://github.com/sanlike0911/node-red-contrib-tplink-tapo-connect-api/commit/0b6f751cc31c0b3869ef06d81dfe071a922e1378)

sanlike0911
