### ISSUE TITLE
Node Red Fails to Start after Upgrade to 0.3.2

### ISSUE THREAD

**Issue by kevinmarchant** [sanlike0911/node-red-contrib-tplink-tapo-connect-api#17]
Just upgraded from 0.3 to 0.3.2 and now node.red fails to start

`5 Jun 18:00:41 - [info] Node-RED version: v2.2.2
5 Jun 18:00:41 - [info] Node.js  version: v16.15.1
5 Jun 18:00:41 - [info] Windows_NT 10.0.19044 x64 LE
5 Jun 18:00:42 - [info] Loading palette nodes
5 Jun 18:00:42 - [error] Failed to start server:
5 Jun 18:00:42 - [error] TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.addModule (C:\Users\kevin\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\registry\lib\registry.js:195:27)
    at C:\Users\kevin\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\registry\lib\loader.js:153:34`

Reverting to 0.3.0 and all is well.

Log attached.

**Comment by sanlike0911** [comment]
Thank you for using node-red-contrib-tplink-tapo-connect-api.

You apologize for any inconvenience.
I will investigate and fix the problem.

**Comment by sanlike0911** [comment]
I fixed the bug.
Could you confirm the "node-red-contrib-tplink-tapo-connect-api@0.3.3"?

**Comment by kevinmarchant** [comment]
Many thanks.  Fixed.

I've upgraded to 0.3.3 and it is working again.  Now to look at the new functionality you've added.
