### ISSUE TITLE
P100 Toggle not working

### ISSUE THREAD

**Issue by mark-harding** [sanlike0911/node-red-contrib-tplink-tapo-connect-api#18]
Status, on and off all work.

Toggle : connect ETIMEDOUT

**Comment by sanlike0911** [comment]
Hi.
Thank you for using this node-red-contrib-tplink-tapo-connect-api.

This node-red-contrib-tplink-tapo-connect-api is a wrapper for 'tp-link-tapo-connect'. I have contacted the developer about this issue.

https://github.com/dickydoouk/tp-link-tapo-connect/issues/31
Please be patient.

sanlike0911

**Comment by sanlike0911** [comment]
Hi.

This problem has been fixed in version 0.3.4.
[#0b6f751](https://github.com/sanlike0911/node-red-contrib-tplink-tapo-connect-api/commit/0b6f751cc31c0b3869ef06d81dfe071a922e1378)

sanlike0911
