### ISSUE TITLE
Enhancement: Retrieve Plug Status via p100.getDeviceInfo() ?

### ISSUE THREAD

**Issue by kevinmarchant** [sanlike0911/node-red-contrib-tplink-tapo-connect-api#2]
Thanks for the Node - excellent !!

It would be useful to be able to query a plug's status (on or off).  Might this be done via p100.getDeviceInfo() and included in the Node ?

**Comment by sanlike0911** [comment]
Hi, Thank you for using "node-red-contrib-tplink-tapo-connect-api".

It will be supported in the next update.

**Comment by sanlike0911** [comment]
Add "255: Get device information" to the payload input.
[INPUT]
msg.payload = 255

You can receive the following results:
[OUTPUT]
msg.payload = {
     device_id: xxxx,
     device_on: <boolean [false or true]>,  <<<< true:on, false:off
     ...,
}

You can tell if the device is on or off by getting "device_on".

**Comment by kevinmarchant** [comment]
Thanks !

Currently upgrading my PC so may be a few days before I can test but I appreciate the effort :-)

**Comment by kevinmarchant** [comment]
Excellent - works a treat!  I've now got a button on my SteamDesk that can toggle my room lights on and off!  

I'm new to Node-Red so there may well be an easier way of doing this but here's my flow.  What would have been really handy is to have the Node itself have a toggle option, e.g 0 for Off, 1 for On, and "-1" for toggle state which incorporated the steps between the two http bits down into a single operation.  But that's just me being lazy but thought I'd mention it in case you were thinking similar :-)

Once again, thanks for your efforts !

![Capture](https://user-images.githubusercontent.com/16034629/130488630-6c4f0126-1001-442a-86b9-9692e99301a6.JPG)

**Comment by sanlike0911** [comment]
Thank you, too.

Thank you for your wonderful hint.
I will add "toggle mode" to the next version.
>What would have been really handy is to have the Node itself have a toggle option

Well then, this issue is closed.
Thank you very much.
